### ISSUE TITLE
Make sure we are c99

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#110]
## Why

We want to target our code for the c99 standard.

## Tasks
- [x] Remove use of  stpcpy
- [x] Remove use of  strnlen
- [x] Remove use of  getline
- [x] Enable `make code-check` in the pipeline to avoid this to become a problem again.

**Comment by juniorz** [comment]
Why not to use gnulib?

https://www.gnu.org/software/gnulib/manual/html_node/Initial-import.html#Initial-import

**Comment by claucece** [comment]
Check this: https://travis-ci.org/otrv4/libotr-ng/builds/278319205?utm_source=github_status&utm_medium=notification

**Comment by olabini** [comment]
We should add -std=c99 to all compile commands

**Comment by olabini** [comment]
We should also add the `-pedantic-errors` flag so the compiler errors when using non-C99 features.

**Comment by claucece** [comment]
Thanks! @olabini
