### ISSUE TITLE
Check full backwards compatibility with libotr

### ISSUE THREAD

**Issue by yakiradixon** [twstrike/libotrv4#32]
## Why

The library should be backwards compatible with libotr.

## References

See https://github.com/otrv4/otrv4/issues/48

## Tasks
- [ ] Check what is missing from libotr to be "fully" compatible.
- [ ] Check that all callbacks are working.
- [ ] Check that everything from the bottom list is covered.

## Open questions

None.

**Comment by claucece** [comment]
To check: 
- [ ] Meta instance tags
- [ ] Fragmentation
- [ ] Context
- [ ] Resend messages by time: lastsent,lastrec
- [ ] OTR offer
- [x] Check OtrlSessionIdHalf for ssid
- [ ] Old mac keys on context_priv
-  [ ] Other error codes from otrv3
- [ ] Logged in
- [ ] Disconnect all instances
- [ ] otrl_message_poll_get_default_interval
- [ ] privkey.h
- [ ] tlv.h
- [ ] version.h and m4
- [ ] possibly: #14 
- [ ] priv, fingerprints from libotr3

**Comment by claucece** [comment]
Also check: 
- [ ] fingerprint_seen_otr3 seems a bit shortsighted. maybe we should just give a "version" argument to fingerprint_seen instead?
- [ ] Implement or check most of the otrv4_client_callbacks_ functions

**Comment by olabini** [comment]
When it says backwards compatible, it doesn't actually mean backwards compatible - it means all the functionality should still work and be available, but not with the same API.

**Comment by olabini** [comment]
After discussion about this, most of this is probably done - although we need to make sure the otr3 callbacks work correctly.
