### ISSUE TITLE
Take the shared prekey and phi from the client

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#47]
## Why

A library should be able to take values from a client and not use dummy values. 

## Reference

Replace dummy values introduced on 208388bbd9d1ff606f319bed7f22259a19d0ce49

## Tasks
- [x] Check that `phi_val` variable needs to be actually a char. 
- [x] On otrng.c, check this code and remove the dummy value:

```
char *phi_val = NULL;
    if (!phi) {
      phi = "";
    }
    phi_val = otrng_strdup(phi);
    if (!phi_val)
      return ERROR;
```

- [x] On otrng.c, remove the dummy value (notice that this variable name is wrong as this is not the symm key):

```
uint8_t sym_key[ED448_PRIVATE_BYTES] = {0x01};
```

- [x] Create a functionality to take these values from the client.

## Depends on/related to

- Issue #58 

## Open questions

- Are all the types used on this functionality correct?

**Comment by juniorz** [comment]
It should be enough to do only the part that is in libotr-ng: provide a way to input `phi` and the shared prekey when a messages needs them.

I propose merging the `phi` part with #58 and leaving this as generating the shared prekey.

**Comment by olabini** [comment]
Maybe make an API in libotr-ng that specifies the different things that can go in to `phi` - for example `alice_identity`, `bob_identity`, `prearranged_password`

**Comment by juniorz** [comment]
In order to generate `phi'`, the protocol expects to receive 3 string parameters:
- 2 identifiers (one per participants).
- a password (optionally).

The `phi'` string is created by joining the 2 identifiers (in lexicographical order). If a password is provided, it is appended to the end of this session state string.

The shared session state string is then generated by joining the 2 participants' instance tags (in numerical order), the query message, and the `phi'` string.

**Comment by juniorz** [comment]
- [x] Update the spec.

**Comment by deniscostadsc** [comment]
Cases like [this](https://github.com/otrv4/libotr-ng/blob/a6375d6f94136e6256f1bee39029585e222771d4/src/otrng.c#L109) should also have a segfault if not implemented? If yes I going to remove this checks from these if's.

**Comment by claucece** [comment]
> Cases like this should also have a segfault if not implemented? If yes I going to remove this checks from these if's.

We already discussed over IRC around this the other day. Right now we are not dealing with these errors as they are part of the plugin/client work. We will deal with them once we start there. So, I'll suggest leaving it there.

**Comment by juniorz** [comment]
These are not callbacks that receive value from outside, bur rather inform the outside that something happened.

If the outside does not want to be informed, the protocol can still move on.

**Comment by claucece** [comment]
Yeah, still for things that inform the outside, I'll prefer to leave them as that for the moment and deal with them in the plugin work. 

I'll say that we should inform, but we will see on the plugin work..

**Comment by deniscostadsc** [comment]
Ok! Thanx!
