### ISSUE TITLE
Add discarding flows to receiving the plaintext with whitespace tag

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#54]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include discarding flows to receiving the plaintext with whitespace tag.

## Reference

Please, refer to "Receiving plaintext with the whitespace tag" section on the OTRv4 specification for details.

Consider #14 

## Tasks
- [ ] Check policies at a client level.
- [ ] Queue the message for encrypting and sending it when the participant transitions to the `ENCRYPTED_MESSAGES` state.
- [ ] After that send an Identity message. 
- [ ] After that transition the state to `WAITING_AUTH_R`.

## Open questions

How can be treat policies from clients?

Same as #14

**Comment by claucece** [comment]
@olabini This might be work for later, but should we consider some kind of policies at a plugin level?

**Comment by claucece** [comment]
We are removing this from the protocol, so this is closed.
