### ISSUE TITLE
Correctly delete and store secret information

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#55]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of deleting secret information.

## Reference

Please, refer to the "Interactive DAKE Overview", "Non-Interactive DAKE Overview", "User Profile", "Rotating ECDH Keys and Brace Key as sender" and "Rotating ECDH Keys and Brace Key as receiver".

## Tasks
- [x] Check if using `sodium_mem_zero` and `goldilocks_bzero`. Consider using one of them.
- [x] Check that points are using the correct deletion function as well as scalars (use the ones Mike Hamburg uses on his library)
- [x] Check that every secret information is correctly deleted, as defined on the spec. If not, securely delete it.
- [x] Check how values are stored and for how long. Take into account the long-term values.
- [x] Document which functions are we using to securely delete information. 

## Depends on

- Issue #53

## Open questions

None.

**Comment by claucece** [comment]
For this, it will be also needed to add printfs as debug to see that the keys are been correctly deleted or not. Sometimes on the lib we delete and later pass zeros to other functions.
