### ISSUE TITLE
Check that points are multiplied by the cofactor when needed

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#56]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of safely using points.

## Reference

Please, refer to the "Generating Shared Secrets" section of the OTRv4 spec.

## Tasks
- [x] Check if the encoding function is actually multiplying by cofactor.
- [x] Check if the decoding function is actually multiplying by cofactor.
- [x] Check, without leaking extra information about the value of `K_ecdh`, whether `K_ecdh` is the all-zero value and abort if so.

## Open questions
None.

**Comment by olabini** [comment]
I'm a bit confused here - it seems the tasks are about fragmentation, but the issue says it's about multiplying curve points.

**Comment by olabini** [comment]
Cool. I'll remove these comments since they are not useful anymore. Including this one. =)

**Comment by claucece** [comment]
Consider changing the point serialization function's name to 'encoding' and 'decoding'.
