### ISSUE TITLE
Check the SCALAR and POINT type

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#57]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using POINT and SCALAR type .

## Reference

Please, refer to the "Encoding and Decoding" section of the OTRv4 specification.

## Tasks
- [x] Check the functions are correctly encoding points and scalars.
- [x] Check that everything needed to is encoded as 'POINT'.
- [x] Check that everything needed to is encoded as 'SCALAR'.
- [x] Check when scalars are 56 bytes long and when they are 57 bytes long.

## Open questions

None.
