### ISSUE TITLE
Check and include more values to Phi

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#58]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a more values to the `phi` value .

## Reference

Please, refer to the "Shared Session State" section of the OTRv4 specification.

## Tasks
- [x] Include to the `phi` value the session identifier mandated by the OTRv4 spec.
- [x] Concatenate this prior value to a value set up by the client.
- [x]  Check if one part of the `phi` value is coming correctly from the client.
- [ ] Consider for how long should the `phi` value live before been deleted.

## Open questions

For how long should the `phi` value live?

**Comment by olabini** [comment]
This seems to slightly overlap with #47

**Comment by claucece** [comment]
@olabini #47 is more about replacing dummy values introduced and actually taken functionality from client (phi and the shared prekey), whereas this issue is about defining `phi`.

**Comment by olabini** [comment]
Ah, OK. That's why I said "slightly" only... =)

**Comment by deniscostadsc** [comment]
I read the "Shared Session State" section, but still not clear where do this. is it [here](https://github.com/otrv4/libotr-ng/blob/master/src/dake.c#L930)?

**Comment by claucece** [comment]
We can talk tomorrow. I have free time at 12pm, does that work for you? @deniscostadsc
