### ISSUE TITLE
Check the OTR errors

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#59]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using OTR errors.

## Reference

Please, refer to the [OTR Error Messages](https://github.com/otrv4/otrv4/blob/master/otrv4.md#otr-error-messages) section of the OTRv4 spec.

## Tasks
- [x] Check the `otrng_error_message` and if it is correctly used, for example.
- [x] Check if everything that errors on the spec is correctly using this function.
- [x] Check that errors are always at the start position of the message.

## Open questions
- Should we include more error types?

**Comment by annacruz** [comment]
The funcion seems to be working in the right way. All of the calls to the function are also right.
When the function is called it starts to write a new message to be sended, so this new message contains just in the beginning the string '?OTR Error' as specified in the protocol.

**Comment by claucece** [comment]
Hey, @annacruz 

Thanks for looking at this.

> The funcion seems to be working in the right way.

`otrng_error_message` is not the only function used for OTR errors. You also have `receive_error_message`, which is the one that checks for the received messages. This is the function that must check that "?OTR Error:" is at the start position of the message, which currently it seems is not. It is used by using `strstr(const char *haystack, const char *needle)` function, which finds the first occurrence of the substring needle in the string haystack, meaning everywhere on the message not at the beginning. 

Furthermore, this function can cause trouble as it is only checking the error by the number:

`  if (strcmp(&message[18], "2") || strcmp(&message[18], "1")) {`

Furthermore, this function should only display the human readable part of the error message, which it is not, as it is seen on test `test_api_conversation_errors`. The spec specifies: "Display the human-readable error message to the user", not the whole error (with the header, etc). There is a TODO on this function.

**Comment by claucece** [comment]
> Check if everything that errors on the spec is correctly using this function.

This means are all cases where we say to send an error on the library are actually sending and receiving so.

Notice, futhermore, that libotr has many more error codes than the ones we have on the spec and library: https://bugs.otr.im/lib/libotr/blob/master/src/message.h#L27 Should we add something similar? Check what we have: https://github.com/otrv4/libotr-ng/blob/master/src/error.h#L39 For this should we use the enums and mix them with ERROR and SUCCESS? This you can discuss with @olabini 

That is the open question of this issue. ;)

**Comment by annacruz** [comment]
@cherenkov What's the human readable part in:

> ?OTR Error: ERROR_2: OTRNG_ERR_MSG_NOT_PRIVATE_STATE

and


> ?OTR Error: ERROR_1: OTRNG_ERR_MSG_READABLE

**Comment by claucece** [comment]
@annacruz 

As the spec specifies:

"Unreadable message" and "Not in private state message".

**Comment by deniscostadsc** [comment]
> As the spec specifies:
> 
> "Unreadable message" and "Not in private state message".

@claucece do you have any place where this is done? Me and @annacruz look at the code and we couldn't find any example of this human-readable conversion.

**Comment by claucece** [comment]
@deniscostadsc 

That is basically what needs to be done. Check here how the message is injected: https://github.com/otrv4/libotr-ng/blob/master/src/otrng.c#L1099 Over there the change should be done.

**Comment by claucece** [comment]
Check the comment I putted on commit 5849d7cd578d1bdcfd365c27cb443e38a6feeaee

Basically the flow of checking OTR errors is:

1. You check that "?OTR Error: " exists at the beginning of the received message (already checked on the library but wrongly checked -it is not checking at the beginning only-).
2. Check that this error message contains only the allowed errors (1 and 2) and ignore otherwise. This has been removed by the commit.
3. Display the human readable part of the error message to the user.

:)

**Comment by claucece** [comment]
Hey!

Have you thought about including more OTR errors? Or using them outside of the enums that also have ERROR and SUCCESS?

**Comment by annacruz** [comment]
@claucece We don't really know if any other message are necessary in this moment, although I really think that the best approach for the moment is to continue using in the way we are using right now, if we have more error messages to deal with we can think in a better aproach. (I just think that the best approach is the simplest one that works with the scenario we have, if we do more is overengineering)

**Comment by claucece** [comment]
Mmm

> if we do more is overengineering

Why will it be overengineering to state the correct error messages to display, instead of passing a boolean-like ERROR or SUCCESS?

**Comment by annacruz** [comment]
What I understood from the method is that it returns SUCCESS if he was able to send to display an error message and ERROR if it's not. I don't see a reason to return anything different than this since it's returning to display the actual message.

**Comment by claucece** [comment]
> What I understood from the method is that it returns SUCCESS if he was able to send to display an error message and ERROR if it's not. I don't see a reason to return anything different than this since it's returning to display the actual message.

That is not at all what I meant. The open question states: "Should we include more error types?". This means not at a error-related function level, but all over the library.  Libotr3 has, for example, other errors it uses like: OTRL_ERRCODE_MSG_MALFORMED, which is used over the library when a data message is malformed.

**Comment by olabini** [comment]
I do want to point out that it's definitely not overengineering thinking about these kinds of error messages, since ideally they should be part of the specification...

**Comment by claucece** [comment]
@olabini yeah.. we created issue #104 for that.

**Comment by olabini** [comment]
Yeah, I know - I just wanted to point out that when working with a specification, it's not necessarily overengineering, in the same way as it would be in other situations.

**Comment by claucece** [comment]
Yeah, we discussed this with @annacruz and @deniscostadsc . I'll definitely check this. One of the problems with otrv3 spec and the library was precisely that it was not specified enough..

**Comment by annacruz** [comment]
@olabini I realized that I was misunderstanding some stuff, that was the problem.
