### ISSUE TITLE
Correctly use the KDFs

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#60]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using KDFs.

## Reference

Please, refer to the "Key Derivation Functions" section of the OTRv4 spec.

## Tasks
- [x] Only use `KDF_1` on the library.
- [x] Check that we use a correct usageID for each time a KDF is used, as defined on the spec.

## Open questions
- Should we use "OTRv4" as the domain separation for the function?

**Comment by claucece** [comment]
@olabini Do you think we should use "OTRv4" as the domain separation for the function?

**Comment by olabini** [comment]
I personally think using "OTRv4" as the domain separation should be fine. Are there any arguments against?

**Comment by claucece** [comment]
@olabini No. Thanks!

**Comment by juniorz** [comment]
The spec suggest the `KDF_1` function to receive a single `values` parameter. In practice, it leads to using more memory than necessary, since we first need to concatenate everything in a single buffer and later write this buffer to the shake "hash context".

Is there any reason to use this same conceptual API in the concrete `KDF_1` function? Or should we progressively write to the shake context instead?

**Comment by olabini** [comment]
Hi,

There is definitely no need for our API's to look the same as the
conceptual functions in the spec, as long as the output matches.

-- 
 Ola Bini (https://olabini.se)

 "Yields falsehood when quined" yields falsehood when quined.

**Comment by claucece** [comment]
> The spec suggest the KDF_1 function to receive a single values parameter. In practice, it leads to using more memory than necessary, since we first need to concatenate everything in a single buffer and later write this buffer to the shake "hash context".

No, what this actually means is that you take several values, not that you take the concatened buffer. If not, it will say "concatenated buffer" or something similar.

> Or should we progressively write to the shake context instead?

Match how SHAKE is used in the library. ;)

**Comment by juniorz** [comment]
Tasks (to be updated):

- [x] `Fingerprint = KDF_1(0x00 || byte(H), 56)`
- [x] `ECDH h' = KDF_1(0x01 || r, 57)`
- [x] `Brace key = KDF_1(0x02 || k_dh, 32) OR KDF_1(0x03 || brace_key, 32)`
- [x] interactive dake`Mixed shared secret = KDF_1(0x04 || K_ecdh || brace_key, 64)`
- [x] non interactive dake `Mixed shared secret = KDF_1(0x04 || tmp_k || brace_key, 64)`
- [x] `SSID = KDF_1(0x05 || K, 8)`
- [x] `Auth-R t = 0x0 || KDF_1(0x06 || Bobs_User_Profile, 64) || KDF_1(0x07 || Alices_User_Profile, 64) || Y || X || B || A || KDF_1(0x08 || phi, 64)`
- [x] `Auth-I t = 0x1 || KDF_1(0x09 || Bobs_User_Profile, 64) || KDF_1(0x10 || Alices_User_Profile, 64) || Y || X || B || A || KDF_1(0x11 || phi, 64)`
- [x] `tmp_k = KDF_1(0x12 || K_ecdh || ECDH(our_shared_prekey.secret, their_ecdh) || ECDH(sk_hb, their_ecdh) || brace_key, 64)`
- [x] `auth_mac_k = KDF_1(0x13 || tmp_k, 64)`
- [x] `t = KDF_1(0x14 || Bobs_User_Profile, 64) || KDF_1(0x15 || Alices_User_Profile, 64) || Y || X || B || A || their_shared_prekey || KDF_1(0x16 || phi, 64)`
- [x] `Offline Data Message Auth MAC = KDF_1(0x18 || auth_mac_k || t || (KDF_1(0x17 ||
             attached encrypted ratchet id ||
             attached encrypted message id || public ecdh key ||
             public dh key || nonce || encrypted message, 64), 64)`.`
- [x] `Double ratchet initialization r = KDF_1(0x19 || K, 57)`
- [x] `Double ratchet initialization r = KDF_1(0x20 || K, 80)`
- [x] `root_key[i] = KDF_1(0x21 || root_key[i-1] || K, 64)`
- [x] `chain_key_purpose[i][j] = KDF_1(0x22 || root_key[i-1] || K, 64)`
- [x] `chain_key_?[i][j] = KDF_1(0x23 || chain_key_?[i][j], 64).`
- [x] `MKenc = KDF_1(0x24 || chain_key, 32)`
- [x] `MKmac = KDF_1(0x25 || MKenc, 64)`
- [x] `extra_symm_key = KDF_1(0x26 || 0xFF || chain_key_s[i-1][j], 32)`
- [x] `Authenticator = KDF_1(0x28 || MKmac || KDF_1(0x27 || data_message_sections, 64), 64)`
- [x] `c = HashToScalar(0x29 || G || q || A1 || A2 || A3 || T1 || T2 || T3 || m)`

I stopped at section "Offline Conversation Initialization".

**Comment by olabini** [comment]
It seems like a lot of tasks are not finished - at least according to the checklists above - should the issue be closed anyway?

**Comment by claucece** [comment]
@olabini I is waiting to the implementation of the double ratchet algorithm in an out of order way, which has been a really long issue. I'll add the KDFs there, as that is my issue ;)

**Comment by olabini** [comment]
Ah, I see. Thanks.
