### ISSUE TITLE
Include out-of-order fragmentation

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#63]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using the fragmentation.

## Reference

Please, refer to the "Fragmentation" section of the OTRv4 spec.

## Tasks
- [x] Check how the fragmentation is working on data messages and change to the new way.
- [x] Check how the reasembly is working on data messages and change to the new way.
- [x] Receive out of order fragments
- [x] Receive multiple fragmented messages at the same time
- [x] Expire unfinished fragments
## Open questions
None.
