### ISSUE TITLE
Correctly derive the extra symmetric key

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#64]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using the extra symmetric key.

## Reference

Please, refer to the "Extra Symmetric Key" section of the OTRv4 spec.

## Tasks
- [x] Check how the sym key functionality is working and if it can work with a client.
- [x] Check and change the KDF being used in the needed functions.
- [x] Allow to derive other keys from it.
- [x] Check that is derived when skipped message keys are stored.

## Open questions
None.
