### ISSUE TITLE
Consider OTRv4 modes

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#66]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using the OTRv4 modes. Note that we are currently implemeting OTRv3-compatible mode.

## Reference

Please, refer to the "OTRv4 Modes" section of the OTRv4 spec.

## Tasks
- [ ] Check how the library will allow the different modes.
- [ ] Check how a client can know about them.
- [ ] Check how a client can talk between them.

## Open questions
None.

**Comment by claucece** [comment]
See the issue: otrv4/libotr-ng#66

**Comment by olabini** [comment]
Since libotr-ng and pidgin-otrng will not have different modes implemented - only different policies, we can close this issue.
