### ISSUE TITLE
Check how an encrypted message is attached to the Non-Interactive-Auth message

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#68]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of attaching an encrypted message to the Non-Interactive-Auth message.

## Reference

Please, refer to the "Attaching an Encrypted Message to Non-Interactive-Auth Message in XZDH" section of the OTRv4 spec.

## Tasks
- [x] Correctly attach the message to the Non-Interactive-Auth message.
- [x] Correctly initialize the double ratchet algorithm for this case.
- [x] Correctly derive the double ratchet algorithm keys.
- [x] Correctly encrypt and decrypt the message.
- [x] Check that the Non-Interactive-Auth message correctly works.

## Open questions
None.

**Comment by juniorz** [comment]
We have identified the following tasks:

- [x] Fix serialization of XZDH-ENCRYPTED-MSG (Attached Encrypted Ratchet Id, Public ECDH key, Public DH Key)
- [x] Fix serialization of non-interactive auth msg (Prekey Message Id, Client Profile Id, Prekey Profile Id)
- [x] API to access the RSig `c` from both sender and receiver. OR, just generate and send the nonce. (Decision depends on talking to @rosatolen and Nik about why using `c`).
- [x] API to access Prekey Message, (Receiver) Client Profile, (Receiver) Prekey Profile
- [x] Double-check the double-ratchet with @claucece 
- [x] Extract a common data structure to represent the encrypted message on a data message and on a non-interactive auth message.
- [x] Consider if the attached encrypted message should really be optional. Making it mandatory simplifies things considerably.

**Comment by juniorz** [comment]
@claucece and @annacruz , I am marking the task about the double ratcheting as done here. We can review it together later.

**Comment by claucece** [comment]
Hey!

At least for this case, is done. Except for a little change that happened last week on the spec. But it shouldn't matter. 

Thanks!

**Comment by juniorz** [comment]
- [x] Make changes related to otrv4/otrv4#151.

**Comment by juniorz** [comment]
The changes related to otrv4/otrv4#151 will be done as part of #109.
