### ISSUE TITLE
Check how instance tags are managed

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#69]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using Instance Tags.

## Reference

Please, refer to the "Instance Tags" section of the OTRv4 spec.

## Tasks
- [x] Check how instance tags are managed.
- [x] Check how instance tags are been get from the client.
- [x] Correctly use the callbacks for instance tags.
- [x] Correctly test and use them over tests.
- [x] Check how they are used over libotr3 and if we can use them in a similar way.
- [x] Support multiple conversations with the same recipient if they use multiple instance tags. See TODO on line 63 of src/client.c UPDATE: this is for the plugin

## Open questions
None.

**Comment by claucece** [comment]
On this, check

```
The smallest valid instance tag is `0x00000100`. It is appropriate to set the
destination instance tag to `0` when an actual destination instance tag is not
known at the time the message is prepared. If a client receives a message with
the sender instance tag set to less than `0x00000100`, it should discard the
message. Similarly, if a client receives a message with the recipient instance
tag set to greater than `0` but less than `0x00000100`, it should discard the
message.
```

**Comment by claucece** [comment]
Anything related with the client and otrv3 will be checked in the next project ;)
