### ISSUE TITLE
Correctly derive the SSID

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#70]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to clarify how to correctly derive the Secure Session ID (SSID).

## Reference

As defined in the OTRv4 specification, section "Secure Session ID".

## Tasks
- [x] Check that the number of bytes this value has (8-byte) and change it accordingly in the library. 
- [x] Check that there is correct functionality for when a participant requests to see it.
- [x] Check that it is correctly derived on both DAKEs.
- [x] Check that it is part of the secret information for the SMP.

## Open questions
None
