### ISSUE TITLE
Correctly expire the session

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#71]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of expiring the session.

## Reference

Please, refer to the "Session Expiration" section of the OTRv4 spec.

## Tasks
- [x] Correctly calculate MAC keys for stored message keys.
- [x] Modify TLV 1 so it can have MAC keys.
- [x] Correctly set up a secure clock for expiring the session. Found out a secure clock.
- [x] Correctly delete the appropriate keys when the session is expired.
- [x] Correctly reset deleted variables.
- [x] Take the clock time from the client.

## Open questions
None.
