### ISSUE TITLE
Check for secure memory allocation and free

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#81]
## Why

A library should be sufficiently secure in the ways it is written. 

## Tasks
- [ ] Check that all pointers are freed when needed.
- [x] Check that all pointers are nullified when freed.
- [ ] Check that all pointers are correctly allocated.
- [ ] Check that valgrind locally and on the CI machines does not report an error.

## Open questions

None.

**Comment by deniscostadsc** [comment]
This seems to be a very manual and repetitive task. Is there any clever way of doing this?

**Comment by claucece** [comment]
There is ways to check this with valgrind, but sometimes valgrind even fails. So, yes.. this is a manual task. This issue is more about reminding that everyone should do this.

**Comment by annacruz** [comment]
Hey @claucece and @olabini did we have some proof about valgrind fail in our codebase? Did this happened before?

**Comment by claucece** [comment]
@annacruz Yes. See this commit, for example: https://github.com/otrv4/libotr-ng/commit/66ea49547e5d233f983d8d5b7eb370dba5b490f5

Valgrind was not checking that as that part of the code was not tested. 

This one as well: https://github.com/otrv4/libotr-ng/commit/7a384f374c855bcb81f1927e3a8bba94817cc745

There can be more of those cases.

Around nullifying after free, check:
https://github.com/otrv4/libotr-ng/commit/8f40bfad5d75636cfa9b3717c7eaa7514c23e316
https://github.com/otrv4/libotr-ng/commit/3b06c68d7b1bbd620478ed39be14d7677aaedb12

I did add a lot of those, but there can be more to add.

**Comment by claucece** [comment]
Furthermore, this one: https://github.com/otrv4/libotr-ng/commit/de326e5c07bc355d4da21d2d7b711f5134c0a685

was only failing on only one machine over valgrind (the OSX one). So, yeah, valgrind sometimes does not found this kind of things.

**Comment by deniscostadsc** [comment]
I got this sample code from [wikipedia](https://en.wikipedia.org/wiki/Dangling_pointer#Avoiding_dangling_pointer_errors):

```c
#include <assert.h>
#include <stdlib.h>

/* Alternative version for 'free()' */
void safefree(void **pp)
{
    /* in debug mode, abort if pp is NULL */
    assert(pp);
    if (pp != NULL) {               /* safety check */
        free(*pp);                  /* deallocate chunk, note that free(NULL) is valid */
        *pp = NULL;                 /* reset original pointer */
    }
}
```

I'm not suggestion this code exactly, but do you all think a approach like this could help us to solve this `NULL` problem. Because if we are using our `safefree`, the pointer is going to be `free`d as we think is the best way. And it's easy to check the code.

This won't solve the case the the programmer forgot to `free` the pointer.

Opinions, please.

**Comment by olabini** [comment]
Yeah, personally I'm worried that this kind of trick will just hide logic errors. Remember, proper memory allocation is really about thinking properly about the states of all kinds of memory and objects we are working with. So, using something like this would hide more serious problems. And incidentally, double frees are much less problematic than not freeing at all - and double frees will usually blow up - especially assuming you're doing proper testing! =)

**Comment by claucece** [comment]
@deniscostadsc 

I don't think we need something as detailed as that. Just using:

```
free(whatever)
whatever = NULL
```

should be enough.

And yes, I agree with @olabini . We used to have tons of double frees on the tests, and maybe some are still there.. so worth checking.

**Comment by olabini** [comment]
Oh, and BTW. Following the pattern of nulling the variable is good. But don't do it reflexively all over - there are many parts of our code base where we NULL a local variable at the end of a function. This is completely useless and is just cluttering up our code base.

**Comment by claucece** [comment]
@olabini yeah. I think that should be enough for the library per se, for tests is a little bit repetitive to do nullify.

**Comment by deniscostadsc** [comment]
@annacruz and me already checked for `NULL` assignments after `free` on commit cdfb07a.

**Comment by deniscostadsc** [comment]
Functions that probably free pointer inside them:

- [x] look at conversation_free function
- [x] look at gcry_free function // **seems does not belong to our codebase**
- [x] look at otrl_userstate_free function // **seems does not belong to our codebase**
- [x] look at otrl_tlv_free function // **seems does not belong to our codebase**
- [x] look at otrng_client_free function
- [x] look at otrng_client_free_all function
- [x] look at otrng_client_state_free function
- [x] look at otrng_client_state_free_all function
- [x] look at otrng_dake_identity_message_free function
- [x] look at otrng_dake_prekey_message_free function
- [x] look at otrng_data_message_free function
- [x] look at otrng_dh_free function
- [x] look at otrng_fragment_context_free function
- [x] look at otrng_free function
- [x] look at otrng_instag_free function
- [x] look at otrng_keypair_free function
- [x] look at otrng_list_free function
- [x] look at otrng_message_free function
- [x] look at otrng_mpi_free function
- [x] look at otrng_response_free function
- [x] look at otrng_shared_prekey_pair_free function
- [x] look at otrng_tlv_list_free function
- [x] look at otrng_user_profile_free function
- [x] look at otrng_user_state_free function
- [x] look at otrng_userstate_free_all function
- [x] look at otrng_v3_conn_free function
- [x] look at ratchet_free function
- [x] look at tlv_free function

**Comment by deniscostadsc** [comment]
Hey, most of [these functions](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383723408) end with `_free`. But some of them do not follow this pattern, like `otrng_userstate_free_all`. Why?

**Comment by claucece** [comment]
The functions with the `free_all` take variable inputs of the same type (VA_ARGS). They don't free one thing, but several, therefore, they free all they are passed. There is a chapter on 20th Century C around that ;)

**Comment by deniscostadsc** [comment]
> Oh, and BTW. Following the pattern of nulling the variable is good. But don't do it reflexively all over - there are many parts of our code base where we NULL a local variable at the end of a function. This is completely useless and is just cluttering up our code base.

We didn't take a look on this. We'll take this into account.

**Comment by deniscostadsc** [comment]
> The functions with the free_all take variable inputs of the same type (VA_ARGS). They don't free one thing, but several, therefore, they free all they are passed. There is a chapter on 20th Century C around that ;)

I didn't read this chapter yet. :D

**Comment by deniscostadsc** [comment]
function `otrng_list_free` that is used on [this function](https://github.com/otrv4/libotr-ng/blob/76d80a9f84fa0cceb3a013394566447b4ad5430f/src/messaging.c#L46), has a `NULL` assignement below it. But I was looking at [its code](https://github.com/otrv4/libotr-ng/blob/cdfb07a51479554f53702f5f602e7d3143a2c5ab/src/list.c#L64), and based on this [specific line](https://github.com/otrv4/libotr-ng/blob/cdfb07a51479554f53702f5f602e7d3143a2c5ab/src/list.c#L61) it seems it nullify the pointer inside the function.

If true, it's not necessary to null after `otrng_list_free`. Am I following this right?

:heart:

**Comment by deniscostadsc** [comment]
It seems what I see on [this comment](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383935798) is also valid for `otrng_tlv_list_free`. It has some unnecessary `NULL` assignments bellow it.

**Comment by deniscostadsc** [comment]
Me and @annacruz had a good look on the code base looking for frees and `NULL` assignments, and after that I'm more in favor of a approach like the one I proposed [here](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383211529).

Almost part of the team also agree with me and we can see that people automated part of the effort freeing pointer into functions, as we can see [here](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383723408) with the creation of all these functions.

I agree with @olabini  on [his points](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383398477) that doing this we can hide some logic, people already hided the logic and cofused the rest of the team as we can see [here](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383935798). A few functions also do something very simple into it, that goes against what @claucece pointed [here](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383398776), as you can see [this](https://github.com/otrv4/libotr-ng/blob/master/src/mpi.c#L32) or [this](https://github.com/otrv4/libotr-ng/blob/bb112a0c0f5550223e4dbc43cce2fe10dcba0077/src/otrng.c#L267) or [this](https://github.com/otrv4/libotr-ng/blob/ef0a38319469b3a4a5844d04e52f5ff8d21ceb75/src/keys.c#L110) or [this](https://github.com/otrv4/libotr-ng/blob/ef0a38319469b3a4a5844d04e52f5ff8d21ceb75/src/keys.c#L59) functions.

About the problem @olabini mentioned about double free, I understood, from my research (check references below) that double free is an issue, but is not the main problem, one of the worst problems the can show up when using not NULLed pointer that were freed, is Dangling Pointers. Am I wrong?

So, I suggest we remove part of those function that only do something like this:

```c
tstatic void otrng_whatever_free(whatever_s *whatever) {
  destroy_whatever(whatever); // some function even dont do this
  free(whatever)
  whatever = NULL
}
```

I order to place this code in the place where this function is used, as @claucece suggested [here](https://github.com/otrv4/libotr-ng/issues/81#issuecomment-383398776), or we user some approach as I suggest and change the whole code base the have functions that do some safe free.

I know that some of the functions are more elaborated in order to facilitate destroy/free/erase complex data structures, like [this function](https://github.com/otrv4/libotr-ng/blob/cdfb07a51479554f53702f5f602e7d3143a2c5ab/src/tlv.c#L133), but this is not true for all function that free something.

I'd really like to hear your thoughts.

:heart:

REFERENCES:

https://www.researchgate.net/publication/281784645_Preventing_Use-after-free_with_Dangling_Pointers_Nullification
https://cwe.mitre.org/data/definitions/416.html
https://en.wikipedia.org/wiki/Dangling_pointer
https://stackoverflow.com/questions/1025589/setting-variable-to-null-after-free

**Comment by deniscostadsc** [comment]
I ran this command:

```
$ find . -name '*.c' | xargs grep malloc | wc -l
93
```

In order to check if all pointer are correctly free, I should track those allocated with `malloc`, right? Is this the best way to accomplish this?

**Comment by deniscostadsc** [comment]
> > Oh, and BTW. Following the pattern of nulling the variable is good. But don't do it reflexively all over - there are many parts of our code base where we NULL a local variable at the end of a function. This is completely useless and is just cluttering up our code base.

> We didn't take a look on this. We'll take this into account.

Should we add a new check-box the like "Check that all pointers are not nullified twice"?

**Comment by claucece** [comment]
Hey!

Answering all of this. 

> function otrng_list_free that is used on this function, has a NULL assignement below it. But I was looking at its code, and based on this specific line it seems it nullify the pointer inside the function.

I don't understand this. `otrng_user_state_free` nullifies a pointer of type 'list_element_s', NOT the elements inside the list (a list can have other 'list_element_s') . 

> It seems what I see on this comment is also valid for otrng_tlv_list_free. It has some unnecessary NULL assignments bellow it.

Same as above. 

> Me and @annacruz had a good look on the code base looking for frees and NULL assignments, and after that I'm more in favor of a approach like the one I proposed here.
> Almost part of the team also agree with me and we can see that people automated part of the effort freeing pointer into functions, as we can see here with the creation of all these functions.

I still don't agree with this. Automating things is not something we aim in this library. 

> I  agree with @olabini on his points that doing this we can hide some logic, people already hided the logic and cofused the rest of the team as we can see here.

That is not confusing, nor hiding logic. That is the behavior of a linked list that contains list. It is one thing to free and nullify what is inside the list and other to free and nullify the list itself. 

> A few functions also do something very simple into it, that goes against what @claucece pointed here, as you can see this or this or this or this functions.

That is not going against. It is precesely doing so. From your examples:

```
INTERNAL void otrng_mpi_free(otrng_mpi_p mpi) {
  free(mpi->data);
  mpi->data = NULL;
}
```

That frees the data and sets it to null. The same approach I said.

```
INTERNAL void otrng_free(/*@only@ */ otrng_s *otr) {
  if (otr == NULL) {
    return;
  }

  otrng_destroy(otr);
  free(otr);
  otr = NULL;
}
```

This function calls `otrng_destroy`, which destroys the elements inside the structure. The `if (otr == NULL) {` is used as sometimes NULL can come to this function. Then it destroys the data and sets it to null.

```
INTERNAL void
otrng_shared_prekey_pair_free(otrng_shared_prekey_pair_s *prekey_pair) {
  if (!prekey_pair)
    return;

  shared_prekey_pair_destroy(prekey_pair);
  free(prekey_pair);
  prekey_pair = NULL;
}
```

Same comment as above.

```
INTERNAL void otrng_keypair_free(otrng_keypair_s *keypair) {
  if (!keypair)
    return;

  keypair_destroy(keypair);
  free(keypair);
  keypair = NULL;
}
```

Same comment as above. 

```
tstatic void otrng_whatever_free(whatever_s *whatever) {
  destroy_whatever(whatever); // some function even dont do this
  free(whatever)
  whatever = NULL
}
```

Some functions will not do the destroy, and that is ok. Why is so? Because sometimes you want to destroy one pointer, and sometimes you want to destroy a pointer to a structure. A structure holds many values, which should be wipped out, set to zero, destroy once the pointer to the structure goes out of life.  

> About the problem @olabini mentioned about double free, I understood, from my research (check references below) that double free is an issue, but is not the main problem, one of the worst problems the can show up when using not NULLed pointer that were freed, is Dangling Pointers. Am I wrong?

There is no little or main problems when freeing memory. Doing a double free is equally important as nullying, not freeing, etc. We should aim to not have ALL of them.

> I order to place this code in the place where this function is used, as @claucece suggested here, or we user some approach as I suggest and change the whole code base the have functions that do some safe free.

No. When I say free and then nullify, I mean for every pointer. If an structure is a pointer that contains pointer in it, you first have to destroy its elements (by freeing and nullying them), and then the pointer itself to the structure. Doing what you propose destroys only the pointer to the structure, and will not completely destroy it. 

> In order to check if all pointer are correctly free, I should track those allocated with malloc, right? Is this the best way to accomplish this?

Yeah, that is fine. There are other ways of allocating memory than only malloc, though. 

Also, a pointer should be destroyed once it gets out of scope. This means, for example, once a function reaches an error. 

> Should we add a new check-box the like "Check that all pointers are not nullified twice"?

I don't think so. 'Check that all pointers are freed when needed' should be enough.

**Comment by claucece** [comment]
So, I think we should have a talk about pointers/scope/structures in the office, can you connect tomorrow @deniscostadsc ?

**Comment by olabini** [comment]
> function otrng_list_free that is used on this function, has a NULL assignement below it. But I was looking at its code, and based on this specific line it seems it nullify the pointer inside the function.
> 
> If true, it's not necessary to null after otrng_list_free. Am I following this right?

@deniscostadsc - so, this comment has a few misunderstandings in it. First, the nulling of "node" inside call_and_free_node at the end is completely unnecessary and shouldn't be there. 

Second, the nulling of "state" at the end of otrng_user_state_free is also completely unnecessary. However, the nullings of  state->states and the other fields inside state ARE necessary.

**Comment by olabini** [comment]
> function otrng_list_free that is used on this function, has a NULL assignement below it. But I was looking at its code, and based on this specific line it seems it nullify the pointer inside the function.
> 
> If true, it's not necessary to null after otrng_list_free. Am I following this right?

@deniscostadsc - so, this comment has a few misunderstandings in it. First, the nulling of "node" inside call_and_free_node at the end is completely unnecessary and shouldn't be there. 

Second, the nulling of "state" at the end of otrng_user_state_free is also completely unnecessary. However, the nullings of  state->states and the other fields inside state ARE necessary.

> Me and @annacruz had a good look on the code base looking for frees and NULL assignments, and after that I'm more in favor of a approach like the one I proposed here.
> 
> Almost part of the team also agree with me and we can see that people automated part of the effort freeing pointer into functions, as we can see here with the creation of all these functions.

First of all, I'm STRONGLY against that kind of helper function (safefree). It doesn't solve the problems we have, and it just stops people from understanding by adding a sledgehammer.

About all the freeing functions, this is idiomatic C code - when you have a structure, you add a _new and _free function, that is responsible for freeing all the objects inside of that structure. The safefree helper has nothing to do with those helper functions, and wouldn't reduce the need for them.

**Comment by olabini** [comment]
> I agree with @olabini on his points that doing this we can hide some logic, people already hided the logic and cofused the rest of the team as we can see here. A few functions also do something very simple into it, that goes against what @claucece pointed here, as you can see this or this or this or this functions.

About these functions - otrng_mpi_free is doing things correctly - it's freeing and NULLing a _field_. But otrng_free, otrng_shared_prekey_pair_free and otrng_keypair_free are all unnecessarily NULLing their argument at the end of the function.

**Comment by olabini** [comment]
> About the problem @olabini mentioned about double free, I understood, from my research (check references below) that double free is an issue, but is not the main problem, one of the worst problems the can show up when using not NULLed pointer that were freed, is Dangling Pointers. Am I wrong?

No, this is wrong. Double Free happens when the same pointer is freed more than once. This causes segmentation faults most of the time. You stop that by setting the pointer to NULL after freeing it. But that's only necessary if the variable can be reached afterwards.

Dangling Pointers happen when you have a variable or field that is _used_ after being freed. This is a logic problem, and it means someone messed up the code. It can be _hidden_ by setting fields and variables to NULL, but that doesn't fix it.

However, the real problem here is also memory leaks, which happens if you don't free something.

In order to solve all these problems, you need to have discipline and carefulness.

**Comment by olabini** [comment]
> So, I suggest we remove part of those function that only do something like this:

Can you give an example of a function like that? I haven't seen a single one. (And remember, your example works on a variable, it doesn't work on fields)

**Comment by olabini** [comment]
> No. When I say free and then nullify, I mean for every pointer. If an structure is a pointer that contains pointer in it, you first have to destroy its elements (by freeing and nullying them), and then the pointer itself to the structure. Doing what you propose destroys only the pointer to the structure, and will not completely destroy it.

I just want to clarify on this point, because I think people unused to C have taking it a bit too literally. A variable or field should ALWAYS be NULLed after free() - unless that variable or field goes out of scope directly afterwards. This means that you never need to NULL a variable if that variable is not used later in the function. But be careful here - fields and variables are very different, and they mean different things. With variables it's easy to see if they will be used again. With fields it's very hard, so it's safer to just NULL them always (unless you free the structure further down in the same function).

**Comment by annacruz** [comment]
So after remove the unused nullifiers that @olabini pointed out we read about the patterns about pointers and functions in C and decided to check all the functions with `_new` in the name if they have an `_free` and/or `_destroy` destroying the right things. Also we found that any place that calls these `_new` functions called the `_free` or `_destroy` function. We must keep in mind that some functions are not internally called but API called, so the user of the API must call the `_free` function after `_new`.

What we found about these functions are listed in the following table:

function | what allocate | Free/Destroy function
--- | --- | ---
gcry_mpi_new | Part of Libgcrypt |---   
list_new | allocate memory for each element of a list | otrng_list_free  
otrl_instance_tag_new | allocate memory for OtrlInsTag |---   
otrng_client_new | allocate memory for otrng_client_s | otrng_client_free   
otrng_client_state_new | allocate memory for otrng_client_state_s | otrng_client_state_free   
otrng_dake_identity_message_new | allocate memory for dake_identity_message_s | otrng_dake_identity_message_destroy   
otrng_dake_prekey_message_new | allocate memory for dake_prekey_message_s | otrng_dake_prekey_message_free
otrng_data_message_new | allocate memory for data_message_s | otrng_data_message_free
otrng_fragment_context_new | allocate memory for fragment_context_s | otrng_fragment_context_free
otrng_keypair_new | allocate memory for otrng_keypair_s| otrng_keypair_free
otrng_message_new | allocate memory for otrng_message_to_send_s| otrng_message_free
otrng_messaging_client_new | commented function|---   
otrng_new | allocate memory for otrng_s| otrng_free
otrng_response_new | allocate memory for otrng_response_s |  otrng_reponse_free
otrng_shared_prekey_pair_new | allocate memory for otrng_shared_prekey_pair_s | otrng_shared_prekey_pair_free
otrng_tlv_disconnected_new | call otrng_tlv_new |---   
otrng_tlv_new | allocate memory to tlv_s| tlv_free
otrng_tlv_padding_new | allocate memory to len|---   
otrng_user_state_new | allocate memmory to otrng_userstate_s| otrng_user_state_free
otrng_v3_conn_new | allocate memory to otrng_v3_conn_s| otrng_v3_free
ratchet_new | allocate memory to ratchet_s| ratchet_free 
user_profile_new | allocate memory to user_profile_s| otrng_user_profile_free

**Comment by annacruz** [comment]
Another doubt that showed up doing this work is about why sometimes is written `user_state` and sometimes `userstate` ? Can we agree in a pattern to follow?

**Comment by olabini** [comment]
Yeah. It should always be user_state

**Comment by claucece** [comment]
I guess we can unassign this issue and keep it open, so people check this when coding in the library, or in general checking it.

**Comment by olabini** [comment]
I would prefer to close issues where we have finished the main task, otherwise we will have a large amount of open tasks that can't be done. I would suggest we add a file of "things to remember" or something like that, with these kind of prescriptions.

**Comment by claucece** [comment]
Yes! We can add that to the style file. Thanks!!
