### ISSUE TITLE
Check that Old Mac keys are correctly revealed

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#82]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of revealing MAC keys.

## Reference

Please, refer to the "Revealing MAC keys" section of the OTRv4 spec.

## Tasks
- [x] Check that the list of the old mac keys is correctly set up.
- [x] Check that all old mac keys are included in the appropriate list.
- [x] Check that TLV type 1 reveals some MAC keys. 
- [x] Reveal MAC keys of skipped stored messages keys.
- [x] Check that MAC keys are derived from the message key.
- [x] Correctly derive the MAC keys for the non-interactive DAKE.

## Open questions
None.

**Comment by claucece** [comment]
This issue is basically solved, but is waiting on the double ratchet in out-of-order, to derive the old mac keys of stored messages.
