### ISSUE TITLE
Check all macros for correct behavior

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#91]
## Why

A library should be sufficiently secure in the ways it is written. 

## Reference

21st Century C, Chapter 8, "Cultivate robust and flourishing macros"

## Discussion

All declarations can be at the head of the block or let them happen as needed.

## Tasks
- [x] Check for the usage of parens in them.
- [x] Avoid double usage.
- [x] Add curly braces for blocks.

## Open questions

None.

**Comment by olabini** [comment]
In general, we shouldn't use very many macros at all.

**Comment by claucece** [comment]
> In general, we shouldn't use very many macros at all.

Yeah.. also that.. ;)

**Comment by claucece** [comment]
Thanks for checking this ;)

**Comment by olabini** [comment]
=D

It's important for us to keep discipline around macros - even though ones we use for tests etc. If we can get away with static inline functions instead, it's better - the way I replaced the accessor macros in otrng.c

**Comment by claucece** [comment]
> f we can get away with static inline functions instead, it's better 

Exactly, I definitely like them better :)
