### ISSUE TITLE
Check the usage of booleans

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#96]
## Why

A library should be sufficiently consistent in the ways it is written. 

## Reference

21st Century C, Chapter 8, "True and False", page 147.

## Discussion

When should be use bool.h? Are errors behaving the same as booleans? 

## Tasks
- [x] Discuss when should we use bool.h
- [x] Discuss how errors are been used and if they should have a similar "boolean" behavior
- [x] Check that if statements are checking by `if (x)` and not `if(x == true)`.

## Open questions

- The issue itself.

**Comment by claucece** [comment]
The way we are using our booleans is kinda weird:
False or error is always 1 and true or success is always 0. This is not compatible with libgoldilocks, where `GOLDILOCKS_TRUE` is -1 and `GOLDILOCKS_FALSE` is 0.

**Comment by olabini** [comment]
Yeah, this is getting horrible... Honestly, have success being 0 makes code like what you pushed yesterday super confusing:
```
  if (otrng_ecdh_valid_secret(k_ecdh))
     return otrng_false;
```
This _will_ cause bugs, and probably already have...

So. Why did we do it this way, do you remember?

**Comment by claucece** [comment]
> Yeah, this is getting horrible... Honestly, have success being 0 makes code like what you pushed yesterday super confusing:

Yes. This is everywhere. I'll prefer using the standard C way for this, meaning 0 is false.  

> This will cause bugs, and probably already have...

Well, there are not. I did manually check them long time ago by doing everywhere: 

```
if (otrng_ecdh_valid_secret(k_ecdh) == otrng_false)
     return otrng_false;
```

And you have no idea how many bugs there were ;)

> So. Why did we do it this way, do you remember?

They were introduced at this commit: https://github.com/otrv4/libotr-ng/commit/0a6eacf3e7099a7a7f0f8d3b2cf1801943a0a651

I'll go for changing that.

**Comment by olabini** [comment]
Hahaha, I believe you! I didn't know you had done that. Very good. Or bad. 
I'll investigate a bit and then we make a decision.

**Comment by olabini** [comment]
OK, after some investigation: can we please use just stdbool? I'm not a huge fan of it, but I think, let's just do it and get this done?
As soon as I you give goahead for a solution, I'll go through and fix every place.

**Comment by olabini** [comment]
And btw, I think error handling is a separate enough issue that maybe we should create a new issue for it?

**Comment by claucece** [comment]
> I didn't know you had done that. Very good. Or bad.

Yeah. On several commits. 

> OK, after some investigation: can we please use just stdbool? I'm not a huge fan of it, but I think, let's just do it and get this done?

I don't like that. But if you think that is good, you can do that. 

> And btw, I think error handling is a separate enough issue that maybe we should create a new issue for it?

There is an issue around OTR errors (#59 ), is that what you mean?

**Comment by olabini** [comment]
Sure, if you don't like it, let's do something else. What's your proposal?

About errors, I was answering to this point "Discuss how errors are been used and if they should have a similar "boolean" behavior" from your description.

**Comment by claucece** [comment]
> Sure, if you don't like it, let's do something else. What's your proposal?

Change the booleans to -1 if true and 0 if false, ala goldilocks. But stdbool is fine. 

> About errors, I was answering to this point "Discuss how errors are been used and if they should have a similar "boolean" behavior" from your description.

There are too kind of boolean-like things we have: `otrng_bool_t` and `otrng_err_t`. I was wondering if we should only use one of that types, or if it makes sense to have both.

**Comment by olabini** [comment]
I'm fine with -1 and 0. But my question is more, should we define constant names for things, should we keep the otrng_false and otrng_true thing, will they be enums or something else, etc.

I think there's a good reason to have otrng_bool_t and otrng_err_t be different. Especially because it feels to me like we could sometime expand otrng_err_t and have different types of errors possible to return.

**Comment by claucece** [comment]
> But my question is more, should we define constant names for things, should we keep the otrng_false and otrng_true thing, will they be enums or something else, etc.

Right now, it is using `static const` for those booleans. I'll go for either that or #define . But, yeah, I guess that is better stdbool as you said. 

> I think there's a good reason to have otrng_bool_t and otrng_err_t be different. Especially because it feels to me like we could sometime expand otrng_err_t and have different types of errors possible to return.

Yeah. Although both `STATE_NOT_ENCRYPTED` and `MSG_NOT_VALID` are functionally only used one, so we should probably use more meaningful errors, instead of always having success or error.

**Comment by olabini** [comment]
Yeah. about the errors. Maybe have a helper function bool is_error(otrng_error_t) or something like that.

**Comment by claucece** [comment]
What was I actually going to was like this, as Mike does it:

https://github.com/otrv4/libgoldilocks/blob/master/src/public_include/goldilocks/common.h#L76
 
It has a `goldilocks_succeed_if` and `goldilocks_successful` functions.

**Comment by olabini** [comment]
Yeah, that's fine too, of course!

**Comment by deniscostadsc** [comment]
On [this commit](https://github.com/otrv4/libotr-ng/commit/199fb351dc9a32541b7783f30570dd9a19593dd7) I started this refactoring.

This commit changes the `otrng_err` enum, to use compliant values on `ERROR` and `SUCCESS`. Now is like this:

```
typedef enum {
  SUCCESS = 1,
  ERROR = 0,
  STATE_NOT_ENCRYPTED = 0x1001,
  MSG_NOT_VALID = 0x1011,
}
```

This means that in `if`s you call a function that return `SUCCESS` or `ERROR`, you can rely on that return. Something like this.

```
if (otrng_close(newmsg, conv->conn))
```

or

```
if (!otrng_close(newmsg, conv->conn))
```

Instead of:

```
if (otrng_close(newmsg, conv->conn) == ERROR)
```

The next steps are:

- refactor the otrng_bool, that has similar problem;
- split the states from otrng_err from the boolean part;
- choose and implement a way to represent booleans values;
- Remove the bool comparison inside `if`s and asserts.

**Comment by deniscostadsc** [comment]
I just realized I messed up with commits linked on this issue (actually I think Github is messing up things, but ok).

These two are the only commits that went into master. Ignore commit above:

https://github.com/otrv4/libotr-ng/commit/389b4c1ed8501875c4b0c8b4d4e98d8ebfe25bed
https://github.com/otrv4/libotr-ng/commit/e57ac6c1ba0c2e0c73c63afb0132f48e1ba4d267

I'll try to add `[WIP]` in all ignorable commit. To be easy recognize which ones are good which are not.

**Comment by olabini** [comment]
Actually, there's a big problem with this refactoring. Specifically, the previous use of the otrng_err allowed for several different values to be errors. However, with the current refactoring, only ERROR will be a negative, and  STATE_NOT_ENCRYPTED or MSG_NOT_VALID will be success. I really don't think that's workable, actually. It will cause too much trouble. My suggestion would be that we split this functinoality into two pieces - a return value that is always a boolean, and an argument where the function can return extra error information if necessary.

**Comment by claucece** [comment]
Yes.. STATE_NOT_ENCRYPTED, MSG_NOT_VALID or similar should not be part of the otrng_err.

**Comment by deniscostadsc** [comment]
> Actually, there's a big problem with this refactoring. Specifically, the previous use of the otrng_err allowed for several different values to be errors. However, with the current refactoring, only ERROR will be a negative, and STATE_NOT_ENCRYPTED or MSG_NOT_VALID will be success. I really don't think that's workable, actually. It will cause too much trouble. My suggestion would be that we split this functinoality into two pieces - a return value that is always a boolean, and an argument where the function can return extra error information if necessary.

OK. So, those function should return `otrng_bool` and receive a pointer that is going to have that state of execution.

**Comment by deniscostadsc** [comment]
About the point @olabini rose, I discussed quickly about @claucece. We think it's better to change that on a issue related with message errors.

Is it ok?

**Comment by olabini** [comment]
Well, sure. But it seems like you'll be doing a lot of duplicated work, since several things you're doing now will need to be undone when the other change is done.

**Comment by claucece** [comment]
@deniscostadsc @olabini Let's talk this on the call tomorrow. I've been thinking that @deniscostadsc needs to move to another story at this point.

**Comment by olabini** [comment]
Yeah, let's talk.

**Comment by claucece** [comment]
This is still missing to use everywhere the wrappers and to return the correct error codes (as parameters to the functions).

**Comment by claucece** [comment]
@giovaneliberato for q/a

**Comment by giovaneliberato** [comment]
I reviewed all the commits for this issue + comments and everything seems right.
There is still some 2 or 3 open comments with suggestions. I checked the code and all of them are solved.

Moving it to done.
